name: birdclef
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.12
  - numpy>=2.1.3
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - pip 
  - papermill
  - scikit-learn
  - pytorch
  - tensorflow
  - keras
  - transformers
  - statsmodels
  - librosa
  - pydub
  - torchaudio
  - timm
  - cartopy
  - snakemake
